CI: Install PostgreSQL in /LibraryPostgreSQL on MacOS
Because this is the default install location and pg/libpq prints an error message when not there:

<internal:/Users/runner/.rubies/ruby-head/lib/ruby/3.2.0+2/rubygems/core_ext/kernel_require.rb>:85:in `require': dlopen(/Users/runner/.rubies/ruby-head/lib/ruby/gems/3.2.0+2/gems/pg-1.4.4/lib/pg_ext.bundle, 9): Library not loaded: /Library/PostgreSQL/14/lib/libpq.5.dylib (LoadError)
  Referenced from: /Users/runner/.rubies/ruby-head/lib/ruby/gems/3.2.0+2/gems/pg-1.4.4/lib/pg_ext.bundle
  Reason: image not found - /Users/runner/.rubies/ruby-head/lib/ruby/gems/3.2.0+2/gems/pg-1.4.4/lib/pg_ext.bundle
	from <internal:/Users/runner/.rubies/ruby-head/lib/ruby/3.2.0+2/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/runner/.rubies/ruby-head/lib/ruby/gems/3.2.0+2/gems/pg-1.4.4/lib/pg.rb:49:in `block in <module:PG>'
	from /Users/runner/.rubies/ruby-head/lib/ruby/gems/3.2.0+2/gems/pg-1.4.4/lib/pg.rb:37:in `block in <module:PG>'
	from /Users/runner/.rubies/ruby-head/lib/ruby/gems/3.2.0+2/gems/pg-1.4.4/lib/pg.rb:42:in `<module:PG>'
	from /Users/runner/.rubies/ruby-head/lib/ruby/gems/3.2.0+2/gems/pg-1.4.4/lib/pg.rb:6:in `<top (required)>'
	from <internal:/Users/runner/.rubies/ruby-head/lib/ruby/3.2.0+2/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/Users/runner/.rubies/ruby-head/lib/ruby/3.2.0+2/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/Users/runner/.rubies/ruby-head/lib/ruby/3.2.0+2/rubygems/core_ext/kernel_require.rb>:149:in `require'
<internal:/Users/runner/.rubies/ruby-head/lib/ruby/3.2.0+2/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- pg (LoadError)
	from <internal:/Users/runner/.rubies/ruby-head/lib/ruby/3.2.0+2/rubygems/core_ext/kernel_require.rb>:85:in `require'
Error: Process completed with exit code 1.