Update rubygems to a ruby-2.5 compatible version
Latest version fails on ruby-2.5 like so:

$ gem update --system
ERROR:  Error installing rubygems-update:
	There are no versions of rubygems-update (= 3.4.3) compatible with your Ruby & RubyGems
	rubygems-update requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass