Remove x86-mingw32 from binary builds
It fails with OpenSSL linker error:
```
configure:13021: i686-w64-mingw32-gcc -o conftest.exe -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation  -I/home/runner/work/ruby-pg/ruby-pg/ports/x86-mingw32/include -D_POSIX_C_SOURCE -I./src/include/port/win32  -L/home/runner/work/ruby-pg/ruby-pg/ports/x86-mingw32/lib -L/home/runner/work/ruby-pg/ruby-pg/ports/x86-mingw32/lib64 -L/home/runner/work/ruby-pg/ruby-pg/ports/x86-mingw32/lib-arm64   -Wl,--allow-multiple-definition -Wl,--disable-auto-import  conftest.c -lcrypto  -lm -lssl -lwsock32 -lgdi32 -lws2_32 -lcrypt32 >&5
/usr/bin/i686-w64-mingw32-ld: /home/runner/work/ruby-pg/ruby-pg/ports/x86-mingw32/lib/libcrypto.a(libdefault-lib-cipher_aes_cfb_hw.obj):cipher_aes_cfb_hw.c:(.text+0x1ea): undefined reference to `ossl_aes_cfb128_vaes_enc'
/usr/bin/i686-w64-mingw32-ld: /home/runner/work/ruby-pg/ruby-pg/ports/x86-mingw32/lib/libcrypto.a(libdefault-lib-cipher_aes_cfb_hw.obj):cipher_aes_cfb_hw.c:(.text+0x220): undefined reference to `ossl_aes_cfb128_vaes_dec'
```

x86-mingw32 is no longer supported by RubyInstaller-4.0 and it seems to be more effort than use.