Fix TcpGateSwitcherProcess on Appveyor on Windows
It fails for some reason when STDIN is used to send the ruby code, although it works on other Windows systems:
```
3) PG::Connection connects without port and then retrieves the default port
     Failure/Error: server_uri = io.gets.strip
     NoMethodError:
       undefined method 'strip' for nil
      ./spec/helpers/tcp_gate_switcher_process.rb:38:in 'Helpers::TcpGateSwitcherProcess#initialize'
      ./spec/pg/connection_spec.rb:902:in 'block (2 levels) in <top (required)>'
      ./spec/helpers.rb:64:in 'block in PG::TestingHelpers.included'
```