CI: Remove ruby < 3.2 from test matrix on Windows
Ruby < 3.2 is not compatible to gcc-15 and patches will not be backported since it's EOL now.
Unfortunately MSYS2 is a rolling release with no option for an older gcc.
Althought setup-ruby installs an older gcc-14.2 package by default, it fails to install further packages per pacman due to dependencies:

```sh
  $ pacman.exe -Sy --noconfirm --noprogressbar --needed --disable-download-timeout  mingw-w64-x86_64-postgresql
  resolving dependencies...
  looking for conflicting packages...
  error: failed to prepare transaction (could not satisfy dependencies)
  :: installing mingw-w64-x86_64-gcc-libs (15.1.0-8) breaks dependency 'mingw-w64-x86_64-gcc-libs=14.2.0-3' required by mingw-w64-x86_64-gcc
```

Also move "bundle install" before PostgreSQL install, as it disturbs compiling gem extensions somehow.