CI: Update to ruby-3.2
since ruby-3.1 has the well known issue, which is fixed in ruby-3.2:

escape.c:477:51: error: passing argument 3 of 'rb_define_method' from
incompatible pointer type [-Wincompatible-pointer-types]
477 |     rb_define_method(rb_mEscapeExt, "escapeHTML", cgiesc_escape_html,
1);