Fix error on PostgreSQL-9.3
  1) Basic type mapping PG::BasicTypeMapForQueries can be initialized with a custom type registry
     Failure/Error: res = @conn.exec_params( "SELECT $1", [0x3031323334353637], 0, tm )

     PG::IndeterminateDatatype:
       ERROR:  could not determine data type of parameter $1
       ./spec/pg/basic_type_map_for_queries_spec.rb:26:in `exec_params'
       ./spec/pg/basic_type_map_for_queries_spec.rb:26:in `block (3 levels) in <top (required)>'
       ./spec/helpers.rb:32:in `block in included'